apiVersion: v2
name: owlistic
description: Owlistic Helm Chart

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.1"
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.0.1
  - name: postgresql
    condition: postgresql.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 16.0.0
  - name: zookeeper
    condition: zookeeper.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 13.8.2
  - name: kafka
    condition: kafka.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 32.2.5
